apiVersion: v1
kind: Service
metadata:
  name: rag-service
  namespace: {{ .Values.namespace | default "default"}}
spec:
  selector:
    app: rag
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
