{{- if .Values.statefulset }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: takeoff-set
  namespace: {{ .Values.namespace | default "default" }}
spec:
  selector:
    matchLabels:
      app: takeoff-set
  serviceName: "takeoff-set"
  replicas: {{ .Values.replicas }}
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: takeoff-set
    spec:
      containers:
        - name: takeoff
          image: tytn/takeoff:{{ .Values.takeoff_version }}{{- if .Values.gpu }}-gpu{{- else }}-cpu{{- end }}
          imagePullPolicy: Always
          ports:
            - name: takeoff
              containerPort: 3000
            - name: management
              containerPort: 3001
          env:
            - name: TAKEOFF_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: takeoff-secrets
                  key: TAKEOFF_ACCESS_TOKEN
            - name: LICENSE_KEY
              valueFrom:
                secretKeyRef:
                  name: takeoff-secrets
                  key: LICENSE_KEY
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: "{{ $value }}"
            {{- end }}
          volumeMounts:
            - name: config-volume
              mountPath: /code/config.yaml
              subPath: takeoff-config.yaml
            - name: key-volume
              mountPath: /code/models/.keys/cacheKeyfile_22918
              subPath: cacheKeyfile_22918
            - name: takeoff-cache-pvc
              mountPath: /code/models
          resources:
            limits:
              memory: {{ .Values.memory_limit | default "20Gi" }}
              {{- if .Values.gpu }}
              nvidia.com/gpu: {{ .Values.number_of_gpus }}
              {{- end }}
            requests:
              memory: {{ .Values.memory_limit | default "20Gi" }}
              cpu: {{ .Values.cpu_request | default "1" }}
          # livenessProbe:
          #   exec:
          #     command:
          #     - sh
          #     - -c
          #     - "curl -s http://localhost:3000/status | grep 'dead_readers\":{\"'; result=\$?; if [ \$result -eq 1 ]; then exit 0; else exit 1; fi"
          #   initialDelaySeconds: 120
          #   periodSeconds: 5
          #   timeoutSeconds: 10
          #   failureThreshold: 10
          startupProbe:                                                                                                                                                                 
            failureThreshold: 60                                                                                                                                                    
            httpGet:                                                                                                                                                                    
              path: /healthz                                                                                                                                                            
              port: 3000                                                                                                                                                                                                                                                                                                                        
            periodSeconds: 10                                                                                                                                                     
            successThreshold: 1                                                                                                          
            timeoutSeconds: 1
      imagePullSecrets:
        - name: takeoff-regcred
      volumes:
        - name: config-volume
          configMap:
            name: takeoff-config
        - name: key-volume
          configMap:
            name: takeoff-key
  volumeClaimTemplates:
  - metadata:
      name: takeoff-cache-pvc
    spec:
      storageClassName: "gp2" # Adjust based on your needs
      accessModes: ["ReadWriteOnce"]
      # storageClassName: {{ .Values.local_cache.storage_class }}
      resources:
        requests:
          storage: {{ .Values.local_cache.size | default "40Gi"}}
{{- end }}
