apiVersion: v1
kind: Service
metadata:
  name: weaviate-service
  namespace: {{ .Values.namespace | default "default"}}
spec:
  selector:
    app: weaviate
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
