# This is the base config passed to the config map which the takeoff container will use to configure itself. Please
# refer to https://docs.titanml.co/docs/Docs/launching/#configuring-takeoff-using-manifest-files for more information.
takeoff:
  server_config:
    port: 3000
    max_batch_size: 512
  readers_config:
    model_1:
      model_name: TitanML/dummy_model
      device: cpu
      max_batch_size: 1
      consumer_group: generate
    model_2:
      model_name: TitanML/jina-v2-base-en-embed
      device: cuda
      consumer_group: embed
      log_level: debug