# The version of Takeoff you want to use
takeoff_version: 0.14.3
gpu: true

# What namespace to deploy takeoff resources in (default is "default")
namespace: takeoff

# Secrets passed to the Takeoff container as environment variables
# Here you need to add your own access token and license key.
secrets:
  TAKEOFF_ACCESS_TOKEN: ""
  LICENSE_KEY: ""

# Other environment variables passed to the Takeoff container
env:
  TAKEOFF_LOG_LEVEL: INFO
  RUST_LOG: INFO

service:
  type: ClusterIP
  ports:
  - name: takeoff
    port: 3000 # Default TAKEOFF_PORT
    targetPort: takeoff
  - name: management
    port: 3001 # Default TAKEOFF_MANAGEMENT_PORT
    targetPort: management

local_cache:
  enabled: true
  size: 40Gi
  host_path: /.takeoff-cache
  storage_class: microk8s-hostpath

ingress:
  enabled: true
  host: localhost
  paths:
  - path: /takeoff/(.*)
    port_name: takeoff
  - path: /management/(.*)
    port_name: management
