apiVersion: v1
kind: ConfigMap
metadata:
  name: takeoff-config
data:
  takeoff-config.yaml: |
{{ .Files.Get "takeoff-config.yaml" | indent 4 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: takeoff-liveness-check
data:
  liveness-check.py: |
{{ .Files.Get "liveness_check.py" | indent 4 }}