apiVersion: v1
kind: Secret
metadata:
  name: takeoff-secrets
  namespace: takeoff
type: Opaque
data:
  {{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
