apiVersion: v1
kind: Secret
metadata:
  name: takeoff-secrets
  namespace: {{ .Values.namespace | default "default"}}
type: Opaque
data:
  {{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value | b64enc | quote }}
  {{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: takeoff-regcred
  namespace: {{ .Values.namespace | default "default"}}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ .Files.Get ".dockerconfig.json" | b64enc | quote }}